version: '3'
services:
  node:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: ghaim
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0.13
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ghaim
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
